#Maintainer: Mateus Oliveira (mateus.oliveira@icomp.ufam.edu.br)
#        Gabriel Dias (g172441@dac.unicamp.br)
#        Marcio Almeida (m240781@dac.unicamp.br)
#

for_predict: "split_train_txt/valid.txt"


network: "vit_base_patch16_224"
learning_rate: 0.0001
epochs: 10000

reload_model:
  type: False
  data: "11_ago"

optimizer:
  Adam:
    lr: 0.0001

model:
  TimmSimpleCNNgelu:
    network: "vit_base_patch16_224"
    image_size: !!python/tuple [224, 224]
    nchannels: 3
    transformers: True
    pretrained: True
    num_classes: 0
    features_only: True

loss:
  RangeMAELoss: RangeMAELoss

path_to_save_model: "models_h5"

path_save_model: 'models_h5/'
name_model: "vit_base_patch16_224"

evaluate_step: 20000

train:
  batch_size: 180

valid:
  batch_size: 180

test:
  batch_size: 1

train_dataset:
  DatasetBasisSetOpenTransformer3ChNormalize:
    path_data: "dataset_1000/train"
    norm: "z_norm"

valid_dataset:
  DatasetBasisSetOpenTransformer3ChNormalize:
    path_data: "dataset_1000/valid"
    norm: "z_norm"

