#sample_predicted
for_predict: "split_train_txt/valid.txt"
# Funcionou:
# wide_resnet50_2
# cspdarknet53

network: "vit_base_patch16_224"
learning_rate: 0.0001
epochs: 100000000000000000000000000000000000000000000000000000000000000000000

reload_model:
  type: False
  data: "11_ago"

optimizer:
  Adam:
    lr: 0.0001
    #weight_decay: 0.01

model:
  TimmSimpleCNNgelu:
    network: "vit_base_patch16_224"
    image_size: !!python/tuple [224, 224]
    nchannels: 3
    transformers: True
    pretrained: True
    num_classes: 0
    features_only: True

loss:
  RangeMAELoss: RangeMAELoss

path_to_save_model: "models_h5"

#--- path save model
path_save_model: 'models_h5/'
name_model: "vit_base_patch16_224"

#evaluate step mafalda biggest dataset
evaluate_step: 20000

#----- wandb
wandb: False

train:
  batch_size: 180

valid:
  batch_size: 180

test:
  batch_size: 1

train_dataset:
  DatasetBasisSetOpenTransformer3ChNormalize:
    path_data: "/home/mateus/sipaim_code_math/Marcio_IC/tests/dataset_1000/train"
    norm: "z_norm"
    #norm: "min-max"

valid_dataset:
  DatasetBasisSetOpenTransformer3ChNormalize:
    path_data: "/home/mateus/sipaim_code_math/Marcio_IC/tests/dataset_1000/valid"
    norm: "z_norm"
    #norm: "min-max"

